services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${SERVER_HOST}
    env_file: .env
    ports: 
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
      - server-v-node_modules:/app/node_modules
    depends_on:
      database:
        condition: service_healthy
  
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - database-v:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  server-v-node_modules:
    name: "node-v-node_modules"
  database-v:
    name: "database-v"