INSERT INTO users (username, email, password, role, otp) VALUES
('Alice Smith', 'alice.smith@example.com', '$2b$10$hashedpassword1', 'owner', '12345678'),
('Bob Johnson', 'bob.johnson@example.com', '$2b$10$hashedpassword2', 'owner', '12345678'),
('Charlie Brown', 'charlie.brown@example.com', '$2b$10$hashedpassword3', 'owner', '12345678'),
('David Wilson', 'david.wilson@example.com', '$2b$10$hashedpassword4', 'owner', '12345678'),
('Emma Jones', 'emma.jones@example.com', '$2b$10$hashedpassword5', 'owner', '12345678'),
('Frank Miller', 'frank.miller@example.com', '$2b$10$hashedpassword6', 'owner', '12345678'),
('Grace Davis', 'grace.davis@example.com', '$2b$10$hashedpassword7', 'owner', '12345678'),
('Henry Lee', 'henry.lee@example.com', '$2b$10$hashedpassword8', 'owner', '12345678'),
('Isabella Taylor', 'isabella.taylor@example.com', '$2b$10$hashedpassword9', 'owner', '12345678'),
('Jack Anderson', 'jack.anderson@example.com', '$2b$10$hashedpassword10', 'owner', '12345678'),
('Liam Johnson', 'liam.johnson@example.com', '$2b$10$hashedpassword11', 'user', '12345678'),
('Mason Brown', 'mason.brown@example.com', '$2b$10$hashedpassword12', 'user', '12345678'),
('Olivia Davis', 'olivia.davis@example.com', '$2b$10$hashedpassword13', 'user', '12345678'),
('Sophia Garcia', 'sophia.garcia@example.com', '$2b$10$hashedpassword14', 'user', '12345678'),
('Ava Martinez', 'ava.martinez@example.com', '$2b$10$hashedpassword15', 'user', '12345678'),
('Isabella Rodriguez', 'isabella.rodriguez@example.com', '$2b$10$hashedpassword16', 'user', '12345678'),
('Ethan Wilson', 'ethan.wilson@example.com', '$2b$10$hashedpassword17', 'user', '12345678'),
('James Lee', 'james.lee@example.com', '$2b$10$hashedpassword18', 'user', '12345678'),
('Lucas Hall', 'lucas.hall@example.com', '$2b$10$hashedpassword19', 'user', '12345678'),
('Mia Young', 'mia.young@example.com', '$2b$10$hashedpassword20', 'user', '12345678'),
('Amelia King', 'amelia.king@example.com', '$2b$10$hashedpassword21', 'user', '12345678'),
('Harper Wright', 'harper.wright@example.com', '$2b$10$hashedpassword22', 'user', '12345678'),
('Ella Scott', 'ella.scott@example.com', '$2b$10$hashedpassword23', 'user', '12345678'),
('Scarlett Green', 'scarlett.green@example.com', '$2b$10$hashedpassword24', 'user', '12345678'),
('Chloe Adams', 'chloe.adams@example.com', '$2b$10$hashedpassword25', 'user', '12345678'),
('Grace Baker', 'grace.baker@example.com', '$2b$10$hashedpassword26', 'user', '12345678'),
('Lily Gonzalez', 'lily.gonzalez@example.com', '$2b$10$hashedpassword27', 'user', '12345678'),
('Zoe Nelson', 'zoe.nelson@example.com', '$2b$10$hashedpassword28', 'user', '12345678'),
('Samantha Carter', 'samantha.carter@example.com', '$2b$10$hashedpassword29', 'user', '12345678'),
('Victoria Mitchell', 'victoria.mitchell@example.com', '$2b$10$hashedpassword30', 'user', '12345678'),
('Natalie Perez', 'natalie.perez@example.com', '$2b$10$hashedpassword31', 'user', '12345678'),
('Hannah Roberts', 'hannah.roberts@example.com', '$2b$10$hashedpassword32', 'user', '12345678'),
('Megan Turner', 'megan.turner@example.com', '$2b$10$hashedpassword33', 'user', '12345678'),
('Avery Phillips', 'avery.phillips@example.com', '$2b$10$hashedpassword34', 'user', '12345678'),
('Addison Campbell', 'addison.campbell@example.com', '$2b$10$hashedpassword35', 'user', '12345678'),
('Brooklyn Parker', 'brooklyn.parker@example.com', '$2b$10$hashedpassword36', 'user', '12345678'),
('Savannah Edwards', 'savannah.edwards@example.com', '$2b$10$hashedpassword37', 'user', '12345678'),
('Mackenzie Collins', 'mackenzie.collins@example.com', '$2b$10$hashedpassword38', 'user', '12345678'),
('Riley Stewart', 'riley.stewart@example.com', '$2b$10$hashedpassword39', 'user', '12345678'),
('Katherine Sanchez', 'katherine.sanchez@example.com', '$2b$10$hashedpassword40', 'user', '12345678')

INSERT INTO businesses (owner_id, country, city, address, zip_code, business_phone, business_webiste, is_verified) VALUES
(1,"Restaurag Lottas", "Sweden", "Umeå", "Nygatan 22", "90327", "090129551","https://www.lottas.nu", true),
(2,"Sjöbris", "Sweden", "Umeå", "Kajen 10", "90326", "090777123","https://www.sjobris.nu", true),
(3,"Basta", "Sweden", "Umeå", "Västra Rådhusgatan 7", "90326", "0101829221","https://www.restaurangbasta.se/restauranger/umea", true),
(4,"Restaurag Bygden", "Sweden", "Umeå", "Östra Strandgatan 30B", "90333", "0902023341","https://www.bgdn.se", true),
(5,"Köksbaren", "Sweden", "Umeå", "Rådhusesplanaden 17B", "90328", "090135660","https://koksbaren.com", true),
(6,"O'Learys", "Sweden", "Umeå", "Skolgatan 64", "90329", "090125555","https://olearys.com/sv-se/umeaa", true),
(7,"The Bishops Arms", "Sweden", "Umeå", "Renmarkstorget", "90326", "09010090","https://www.bishopsarms.com/vara-pubar/umea", true),
(8,"Harlequin", "Sweden", "Umeå", "Rådhusesplanaden 2E", "90328", "090778588","https://www.harlequinumea.com", true),
(9,"Hunger och Törst", "Sweden", "Umeå", "Vasagatan 1", "90329", "090771000","https://www.hungerochtorst.se", true),
(10,"Kebabnekajse Pizzeria", "Sweden", "Umeå", "Rådhusesplanaden 18B", "90328", "090773939","https://www.kebabnekajsebagen.se", true),

INSERT INTO dishes (business_id, dish_name, description, price) VALUES
(1, 'Högrevsburgare', 'Juicy beef burger with homemade sauce and fries', 150),
(1, 'Fish n’ Chips', 'Crispy fried fish served with chips and tartar sauce', 170),
(1, 'Pasta Carbonara', 'Classic pasta with pancetta, cream, and parmesan', 145),
(1, 'Caesar Salad', 'Romaine lettuce, croutons, and caesar dressing', 120),
(1, 'Mushroom Risotto', 'Creamy risotto with wild mushrooms and herbs', 160),
(1, 'Chocolate Mousse', 'Rich chocolate dessert topped with whipped cream', 90),
(1, 'Tiramisu', 'Classic Italian dessert with coffee and mascarpone', 95),
(2, 'Grilled Salmon', 'Served with seasonal vegetables and lemon butter', 220),
(2, 'Beef Tenderloin', 'Perfectly cooked beef served with red wine sauce', 320),
(2, 'Vegetable Risotto', 'Creamy risotto with fresh seasonal vegetables', 180),
(2, 'Caprese Salad', 'Fresh mozzarella, tomatoes, and basil', 120),
(2, 'Tuna Tartare', 'Fresh tuna with avocado and sesame dressing', 210),
(2, 'Panna Cotta', 'Smooth vanilla cream dessert', 100),
(2, 'Cheese Platter', 'Selection of local cheeses with crackers', 150),
(3, 'Margherita Pizza', 'Classic pizza with tomato sauce and mozzarella', 110),
(3, 'Pasta Primavera', 'Pasta with fresh vegetables and olive oil', 145),
(3, 'Lasagna', 'Layers of pasta, meat sauce, and béchamel', 180),
(3, 'Bruschetta', 'Toasted bread topped with tomatoes and basil', 90),
(3, 'Gnocchi with Pesto', 'Potato dumplings served with pesto sauce', 160),
(3, 'Tiramisu', 'Classic Italian dessert with coffee and mascarpone', 95),
(3, 'Affogato', 'Ice cream topped with hot espresso', 85),
(4, 'Kalix Löjrom', 'Fish roe served with blinis and sour cream', 250),
(4, 'Beef Stew', 'Slow-cooked beef with root vegetables', 220),
(4, 'Grilled Vegetables', 'Mixed seasonal vegetables grilled to perfection', 150),
(4, 'Herring Platter', 'Assorted herring served with potatoes and onions', 180),
(4, 'Rhubarb Pie', 'Homemade pie served with vanilla sauce', 95),
(4, 'Crayfish Soup', 'Rich soup with crayfish and herbs', 160),
(4, 'Chocolate Cake', 'Moist chocolate cake with a rich frosting', 85),
(5, 'Greek Salad', 'Mixed greens with feta cheese and olives', 120),
(5, 'Shrimp Tacos', 'Tacos filled with seasoned shrimp and fresh toppings', 150),
(5, 'Pasta Pesto', 'Pasta tossed with fresh basil pesto', 140),
(5, 'Mushroom Soup', 'Creamy soup made with fresh mushrooms', 100),
(5, 'Chocolate Fondant', 'Warm chocolate cake with molten center', 95),
(5, 'Carrot Cake', 'Moist cake topped with cream cheese frosting', 85),
(5, 'Fruit Salad', 'Fresh seasonal fruits served with a drizzle of honey', 80),
(6, 'Buffalo Wings', 'Spicy chicken wings served with blue cheese dressing', 130),
(6, 'BBQ Ribs', 'Tender ribs glazed with BBQ sauce', 250),
(6, 'Caesar Wrap', 'Chicken Caesar salad wrapped in a tortilla', 140),
(6, 'Nachos', 'Crispy tortilla chips topped with cheese and jalapeños', 120),
(6, 'Veggie Burger', 'Plant-based burger with fresh toppings', 150),
(6, 'Cheesecake', 'Creamy cheesecake topped with berry sauce', 95),
(6, 'Milkshake', 'Thick milkshake in various flavors', 85),
(7, 'Fish and Chips', 'Crispy fish served with fries and mushy peas', 160),
(7, 'Steak and Ale Pie', 'Traditional pie filled with steak and ale', 210),
(7, 'Ploughman’s Lunch', 'Cheese, bread, and pickle platter', 150),
(7, 'Bangers and Mash', 'Sausages served with mashed potatoes and gravy', 180),
(7, 'Vegetarian Shepherd’s Pie', 'A hearty vegetable pie topped with mashed potatoes', 160),
(7, 'Sticky Toffee Pudding', 'Warm pudding served with toffee sauce', 95),
(7, 'Pork Scratchings', 'Crispy pork snacks served with apple sauce', 70),
(8, 'Beef Tartare', 'Raw beef with spices and condiments', 220),
(8, 'Pike Perch', 'Pan-fried pike perch with seasonal vegetables', 240),
(8, 'Wild Mushroom Risotto', 'Creamy risotto with wild mushrooms', 190),
(8, 'Lamb Chops', 'Grilled lamb chops with rosemary sauce', 300),
(8, 'Cauliflower Steak', 'Roasted cauliflower served with tahini sauce', 180),
(8, 'Lemon Tart', 'Refreshing tart with lemon curd', 95),
(8, 'Cheese Platter', 'Selection of local cheeses with crackers', 150),
(9, 'Smoked Salmon', 'Served with cream cheese and capers', 210),
(9, 'Duck Breast', 'Pan-seared duck breast with cherry sauce', 290),
(9, 'Vegan Buddha Bowl', 'Quinoa with mixed vegetables and tahini dressing', 180),
(9, 'Beef Wellington', 'Beef wrapped in pastry with mushroom duxelles', 350),
(9, 'Raspberry Sorbet', 'Refreshing raspberry sorbet', 80),
(9, 'Apple Crumble', 'Warm apple crumble served with vanilla ice cream', 90),
(9, 'Pasta Primavera', 'Pasta with seasonal vegetables in olive oil', 160),
(10, 'Kebab Pizza', 'Pizza topped with kebab meat and fresh veggies', 120),
(10, 'Falafel Wrap', 'Wrap filled with falafel and tahini sauce', 90),
(10, 'Doner Kebab Plate', 'Served with rice and salad', 150),
(10, 'Vegetarian Pizza', 'Pizza topped with various seasonal vegetables', 110),
(10, 'Baklava', 'Sweet pastry filled with nuts and honey', 75),
(10, 'Mango Lassi', 'Refreshing yogurt drink with mango', 60),
(10, 'Spicy Chicken Wings', 'Chicken wings marinated in spicy sauce', 130);
