INSERT INTO users (username, email, password, role, otp) VALUES
('Alice Smith', 'alice.smith@example.com', '$2b$10$hashedpassword1', 'owner', '12345678'),
('Bob Johnson', 'bob.johnson@example.com', '$2b$10$hashedpassword2', 'owner', '12345678'),
('Charlie Brown', 'charlie.brown@example.com', '$2b$10$hashedpassword3', 'owner', '12345678'),
('David Wilson', 'david.wilson@example.com', '$2b$10$hashedpassword4', 'owner', '12345678'),
('Emma Jones', 'emma.jones@example.com', '$2b$10$hashedpassword5', 'owner', '12345678'),
('Frank Miller', 'frank.miller@example.com', '$2b$10$hashedpassword6', 'owner', '12345678'),
('Grace Davis', 'grace.davis@example.com', '$2b$10$hashedpassword7', 'owner', '12345678'),
('Henry Lee', 'henry.lee@example.com', '$2b$10$hashedpassword8', 'owner', '12345678'),
('Isabella Taylor', 'isabella.taylor@example.com', '$2b$10$hashedpassword9', 'owner', '12345678'),
('Jack Anderson', 'jack.anderson@example.com', '$2b$10$hashedpassword10', 'owner', '12345678'),
('Liam Johnson', 'liam.johnson@example.com', '$2b$10$hashedpassword11', 'user', '12345678'),
('Mason Brown', 'mason.brown@example.com', '$2b$10$hashedpassword12', 'user', '12345678'),
('Olivia Davis', 'olivia.davis@example.com', '$2b$10$hashedpassword13', 'user', '12345678'),
('Sophia Garcia', 'sophia.garcia@example.com', '$2b$10$hashedpassword14', 'user', '12345678'),
('Ava Martinez', 'ava.martinez@example.com', '$2b$10$hashedpassword15', 'user', '12345678'),
('Isabella Rodriguez', 'isabella.rodriguez@example.com', '$2b$10$hashedpassword16', 'user', '12345678'),
('Ethan Wilson', 'ethan.wilson@example.com', '$2b$10$hashedpassword17', 'user', '12345678'),
('James Lee', 'james.lee@example.com', '$2b$10$hashedpassword18', 'user', '12345678'),
('Lucas Hall', 'lucas.hall@example.com', '$2b$10$hashedpassword19', 'user', '12345678'),
('Mia Young', 'mia.young@example.com', '$2b$10$hashedpassword20', 'user', '12345678'),
('Amelia King', 'amelia.king@example.com', '$2b$10$hashedpassword21', 'user', '12345678'),
('Harper Wright', 'harper.wright@example.com', '$2b$10$hashedpassword22', 'user', '12345678'),
('Ella Scott', 'ella.scott@example.com', '$2b$10$hashedpassword23', 'user', '12345678'),
('Scarlett Green', 'scarlett.green@example.com', '$2b$10$hashedpassword24', 'user', '12345678'),
('Chloe Adams', 'chloe.adams@example.com', '$2b$10$hashedpassword25', 'user', '12345678'),
('Grace Baker', 'grace.baker@example.com', '$2b$10$hashedpassword26', 'user', '12345678'),
('Lily Gonzalez', 'lily.gonzalez@example.com', '$2b$10$hashedpassword27', 'user', '12345678'),
('Zoe Nelson', 'zoe.nelson@example.com', '$2b$10$hashedpassword28', 'user', '12345678'),
('Samantha Carter', 'samantha.carter@example.com', '$2b$10$hashedpassword29', 'user', '12345678'),
('Victoria Mitchell', 'victoria.mitchell@example.com', '$2b$10$hashedpassword30', 'user', '12345678'),
('Natalie Perez', 'natalie.perez@example.com', '$2b$10$hashedpassword31', 'user', '12345678'),
('Hannah Roberts', 'hannah.roberts@example.com', '$2b$10$hashedpassword32', 'user', '12345678'),
('Megan Turner', 'megan.turner@example.com', '$2b$10$hashedpassword33', 'user', '12345678'),
('Avery Phillips', 'avery.phillips@example.com', '$2b$10$hashedpassword34', 'user', '12345678'),
('Addison Campbell', 'addison.campbell@example.com', '$2b$10$hashedpassword35', 'user', '12345678'),
('Brooklyn Parker', 'brooklyn.parker@example.com', '$2b$10$hashedpassword36', 'user', '12345678'),
('Savannah Edwards', 'savannah.edwards@example.com', '$2b$10$hashedpassword37', 'user', '12345678'),
('Mackenzie Collins', 'mackenzie.collins@example.com', '$2b$10$hashedpassword38', 'user', '12345678'),
('Riley Stewart', 'riley.stewart@example.com', '$2b$10$hashedpassword39', 'user', '12345678'),
('Katherine Sanchez', 'katherine.sanchez@example.com', '$2b$10$hashedpassword40', 'user', '12345678')

INSERT INTO businesses (owner_id, country, city, address, zip_code, business_phone, business_webiste, is_verified) VALUES
(1,"Restaurag Lottas", "Sweden", "Umeå", "Nygatan 22", "90327", "090129551","https://www.lottas.nu", true),
(2,"Sjöbris", "Sweden", "Umeå", "Kajen 10", "90326", "090777123","https://www.sjobris.nu", true),
(3,"Basta", "Sweden", "Umeå", "Västra Rådhusgatan 7", "90326", "0101829221","https://www.restaurangbasta.se/restauranger/umea", true),
(4,"Restaurag Bygden", "Sweden", "Umeå", "Östra Strandgatan 30B", "90333", "0902023341","https://www.bgdn.se", true),
(5,"Köksbaren", "Sweden", "Umeå", "Rådhusesplanaden 17B", "90328", "090135660","https://koksbaren.com", true),
(6,"O'Learys", "Sweden", "Umeå", "Skolgatan 64", "90329", "090125555","https://olearys.com/sv-se/umeaa", true),
(7,"The Bishops Arms", "Sweden", "Umeå", "Renmarkstorget", "90326", "09010090","https://www.bishopsarms.com/vara-pubar/umea", true),
(8,"Harlequin", "Sweden", "Umeå", "Rådhusesplanaden 2E", "90328", "090778588","https://www.harlequinumea.com", true),
(9,"Hunger och Törst", "Sweden", "Umeå", "Vasagatan 1", "90329", "090771000","https://www.hungerochtorst.se", true),
(10,"Kebabnekajse Pizzeria", "Sweden", "Umeå", "Rådhusesplanaden 18B", "90328", "090773939","https://www.kebabnekajsebagen.se", true),

INSERT INTO dishes (business_id, dish_name, description, price) VALUES
(1, 'Högrevsburgare', 'Juicy beef burger with homemade sauce and fries', 150),
(1, 'Fish n’ Chips', 'Crispy fried fish served with chips and tartar sauce', 170),
(1, 'Pasta Carbonara', 'Classic pasta with pancetta, cream, and parmesan', 145),
(1, 'Caesar Salad', 'Romaine lettuce, croutons, and caesar dressing', 120),
(1, 'Mushroom Risotto', 'Creamy risotto with wild mushrooms and herbs', 160),
(1, 'Chocolate Mousse', 'Rich chocolate dessert topped with whipped cream', 90),
(1, 'Tiramisu', 'Classic Italian dessert with coffee and mascarpone', 95),
(2, 'Grilled Salmon', 'Served with seasonal vegetables and lemon butter', 220),
(2, 'Beef Tenderloin', 'Perfectly cooked beef served with red wine sauce', 320),
(2, 'Vegetable Risotto', 'Creamy risotto with fresh seasonal vegetables', 180),
(2, 'Caprese Salad', 'Fresh mozzarella, tomatoes, and basil', 120),
(2, 'Tuna Tartare', 'Fresh tuna with avocado and sesame dressing', 210),
(2, 'Panna Cotta', 'Smooth vanilla cream dessert', 100),
(2, 'Cheese Platter', 'Selection of local cheeses with crackers', 150),
(3, 'Margherita Pizza', 'Classic pizza with tomato sauce and mozzarella', 110),
(3, 'Pasta Primavera', 'Pasta with fresh vegetables and olive oil', 145),
(3, 'Lasagna', 'Layers of pasta, meat sauce, and béchamel', 180),
(3, 'Bruschetta', 'Toasted bread topped with tomatoes and basil', 90),
(3, 'Gnocchi with Pesto', 'Potato dumplings served with pesto sauce', 160),
(3, 'Tiramisu', 'Classic Italian dessert with coffee and mascarpone', 95),
(3, 'Affogato', 'Ice cream topped with hot espresso', 85),
(4, 'Kalix Löjrom', 'Fish roe served with blinis and sour cream', 250),
(4, 'Beef Stew', 'Slow-cooked beef with root vegetables', 220),
(4, 'Grilled Vegetables', 'Mixed seasonal vegetables grilled to perfection', 150),
(4, 'Herring Platter', 'Assorted herring served with potatoes and onions', 180),
(4, 'Rhubarb Pie', 'Homemade pie served with vanilla sauce', 95),
(4, 'Crayfish Soup', 'Rich soup with crayfish and herbs', 160),
(4, 'Chocolate Cake', 'Moist chocolate cake with a rich frosting', 85),
(5, 'Greek Salad', 'Mixed greens with feta cheese and olives', 120),
(5, 'Shrimp Tacos', 'Tacos filled with seasoned shrimp and fresh toppings', 150),
(5, 'Pasta Pesto', 'Pasta tossed with fresh basil pesto', 140),
(5, 'Mushroom Soup', 'Creamy soup made with fresh mushrooms', 100),
(5, 'Chocolate Fondant', 'Warm chocolate cake with molten center', 95),
(5, 'Carrot Cake', 'Moist cake topped with cream cheese frosting', 85),
(5, 'Fruit Salad', 'Fresh seasonal fruits served with a drizzle of honey', 80),
(6, 'Buffalo Wings', 'Spicy chicken wings served with blue cheese dressing', 130),
(6, 'BBQ Ribs', 'Tender ribs glazed with BBQ sauce', 250),
(6, 'Caesar Wrap', 'Chicken Caesar salad wrapped in a tortilla', 140),
(6, 'Nachos', 'Crispy tortilla chips topped with cheese and jalapeños', 120),
(6, 'Veggie Burger', 'Plant-based burger with fresh toppings', 150),
(6, 'Cheesecake', 'Creamy cheesecake topped with berry sauce', 95),
(6, 'Milkshake', 'Thick milkshake in various flavors', 85),
(7, 'Fish and Chips', 'Crispy fish served with fries and mushy peas', 160),
(7, 'Steak and Ale Pie', 'Traditional pie filled with steak and ale', 210),
(7, 'Ploughman’s Lunch', 'Cheese, bread, and pickle platter', 150),
(7, 'Bangers and Mash', 'Sausages served with mashed potatoes and gravy', 180),
(7, 'Vegetarian Shepherd’s Pie', 'A hearty vegetable pie topped with mashed potatoes', 160),
(7, 'Sticky Toffee Pudding', 'Warm pudding served with toffee sauce', 95),
(7, 'Pork Scratchings', 'Crispy pork snacks served with apple sauce', 70),
(8, 'Beef Tartare', 'Raw beef with spices and condiments', 220),
(8, 'Pike Perch', 'Pan-fried pike perch with seasonal vegetables', 240),
(8, 'Wild Mushroom Risotto', 'Creamy risotto with wild mushrooms', 190),
(8, 'Lamb Chops', 'Grilled lamb chops with rosemary sauce', 300),
(8, 'Cauliflower Steak', 'Roasted cauliflower served with tahini sauce', 180),
(8, 'Lemon Tart', 'Refreshing tart with lemon curd', 95),
(8, 'Cheese Platter', 'Selection of local cheeses with crackers', 150),
(9, 'Smoked Salmon', 'Served with cream cheese and capers', 210),
(9, 'Duck Breast', 'Pan-seared duck breast with cherry sauce', 290),
(9, 'Vegan Buddha Bowl', 'Quinoa with mixed vegetables and tahini dressing', 180),
(9, 'Beef Wellington', 'Beef wrapped in pastry with mushroom duxelles', 350),
(9, 'Raspberry Sorbet', 'Refreshing raspberry sorbet', 80),
(9, 'Apple Crumble', 'Warm apple crumble served with vanilla ice cream', 90),
(9, 'Pasta Primavera', 'Pasta with seasonal vegetables in olive oil', 160),
(10, 'Kebab Pizza', 'Pizza topped with kebab meat and fresh veggies', 120),
(10, 'Falafel Wrap', 'Wrap filled with falafel and tahini sauce', 90),
(10, 'Doner Kebab Plate', 'Served with rice and salad', 150),
(10, 'Vegetarian Pizza', 'Pizza topped with various seasonal vegetables', 110),
(10, 'Baklava', 'Sweet pastry filled with nuts and honey', 75),
(10, 'Mango Lassi', 'Refreshing yogurt drink with mango', 60),
(10, 'Spicy Chicken Wings', 'Chicken wings marinated in spicy sauce', 130);

INSERT INTO reviews (business_id, user_id, rating, review) VALUES
(1, 11, 10, 'The beef burger was juicy and full of flavor! Highly recommended.'),
(1, 12, 8, 'Fish n’ Chips were great, but the portion could be larger.'),
(1, 13, 9, 'Loved the pasta carbonara! Creamy and delicious.'),
(1, 14, 7, 'The atmosphere was cozy and inviting. Fantastic service!'),
(1, 15, 6, 'The dessert was good, but a bit overpriced.'),
(1, 16, 10, 'Best Tiramisu I’ve ever had! Will definitely come back.'),
(1, 17, 8, 'Great selection of drinks paired well with the food.'),
(1, 18, 9, 'The staff was friendly and attentive, made us feel welcome.'),
(1, 19, 7, 'Good value for money, will return for sure.'),
(1, 20, 10, 'Perfect place for a family dinner!'),
(2, 21, 10, 'Grilled salmon was perfectly cooked and flavorful.'),
(2, 22, 8, 'Nice view of the river and great service.'),
(2, 23, 10, 'The beef tenderloin was exquisite! Highly recommend.'),
(2, 24, 8, 'Vegetable risotto was delicious but a bit salty.'),
(2, 25, 10, 'Panna Cotta was the best way to finish the meal.'),
(2, 26, 8, 'The atmosphere is lovely, perfect for a romantic dinner.'),
(2, 27, 9, 'Great wine selection that complements the food.'),
(2, 28, 7, 'A bit pricey, but worth it for the quality.'),
(2, 29, 10, 'The staff was very attentive and knowledgeable about the menu.'),
(3, 30, 10, 'Amazing Margherita pizza! Just like in Italy.'),
(3, 31, 8, 'Pasta Primavera was fresh and tasty.'),
(3, 32, 10, 'The lasagna is a must-try! Very comforting.'),
(3, 33, 6, 'Bruschetta was good but lacked seasoning.'),
(3, 34, 9, 'Great atmosphere and friendly staff.'),
(3, 35, 8, 'Affogato is a perfect ending to a lovely meal.'),
(3, 36, 10, 'Excellent service and a cozy environment.'),
(3, 37, 9, 'Good options for vegetarians on the menu.'),
(4, 38, 10, 'Kalix Löjrom was fantastic!'),
(4, 39, 8, 'The beef stew was hearty and delicious.'),
(4, 40, 9, 'Grilled vegetables were perfectly cooked.'),
(4, 41, 8, 'Rhubarb pie was a delightful dessert.'),
(4, 42, 10, 'Crayfish soup was rich and flavorful.'),
(4, 43, 7, 'Chocolate cake was moist and indulgent.'),
(4, 44, 9, 'Great place for a family gathering!'),
(4, 45, 8, 'Service was quick and friendly.'),
(5, 46, 10, 'Greek salad was fresh and vibrant.'),
(5, 47, 8, 'Shrimp tacos were flavorful and filling.'),
(5, 48, 9, 'Pasta pesto was delicious and aromatic.'),
(5, 49, 6, 'Mushroom soup was good but a bit salty.'),
(5, 50, 10, 'Chocolate fondant was heavenly.'),
(5, 51, 8, 'Carrot cake was moist and flavorful.'),
(5, 52, 7, 'Good variety of options on the menu.'),
(6, 53, 10, 'Buffalo Wings were spicy and tasty!'),
(6, 54, 8, 'BBQ Ribs were tender and flavorful.'),
(6, 55, 9, 'The Veggie Burger was surprisingly good.'),
(6, 56, 6, 'Nachos could use more toppings.'),
(6, 57, 10, 'Great atmosphere for watching sports!'),
(6, 58, 8, 'Friendly staff and quick service.'),
(6, 59, 9, 'Perfect spot for a casual night out.'),
(7, 60, 10, 'Fish and Chips were excellent with a crisp batter.'),
(7, 61, 8, 'Steak and Ale Pie was hearty and satisfying.'),
(7, 62, 10, 'The Ploughman’s Lunch was delightful and filling.'),
(7, 63, 8, 'Bangers and Mash were comfort food at its best.'),
(7, 64, 10, 'Sticky Toffee Pudding was a perfect dessert.'),
(7, 65, 8, 'Great selection of beers to choose from.'),
(8, 66, 10, 'Beef Tartare was expertly prepared and flavorful.'),
(8, 67, 8, 'Pike Perch was fresh and well-seasoned.'),
(8, 68, 10, 'Wild Mushroom Risotto was creamy and delicious.'),
(8, 69, 8, 'Lamb Chops were tender and juicy.'),
(8, 70, 10, 'Cauliflower Steak was an excellent vegetarian option.'),
(8, 71, 8, 'Good wine selection that pairs well with the menu.'),
(9, 72, 10, 'Smoked Salmon was fresh and beautifully presented.'),
(9, 73, 8, 'Duck Breast was cooked perfectly with a nice sauce.'),
(9, 74, 10, 'Vegan Buddha Bowl was hearty and filling.'),
(9, 75, 6, 'Beef Wellington was good but a bit overcooked.'),
(9, 76, 10, 'Raspberry Sorbet was refreshing and light.'),
(9, 77, 8, 'Apple Crumble was warm and comforting.'),
(10, 78, 10, 'Kebab Pizza was delicious and filling.'),
(10, 79, 8, 'Falafel Wrap was tasty and satisfying.'),
(10, 80, 9, 'Doner Kebab Plate was great with fresh toppings.'),
(10, 81, 7, 'Vegetarian Pizza was good but could use more flavor.'),
(10, 82, 10, 'Baklava was sweet and flaky, a perfect dessert.'),
(10, 83, 8, 'Mango Lassi was refreshing and delicious.');

INSERT INTO dish_reviews (dish_id, user_id, rating, review) VALUES
(1, 11, 9, 'Juicy and flavorful burger, would order again.'),
(1, 12, 8, 'Nice burger, fries were okay.'),
(1, 13, 10, 'Absolutely loved the sauce and beef.'),
(2, 14, 9, 'Crispy fish, delicious tartar sauce.'),
(2, 15, 8, 'Fish was great but chips a bit greasy.'),
(3, 16, 10, 'Authentic carbonara, creamy and rich!'),
(3, 17, 9, 'Pasta was cooked perfectly, flavorful.'),
(3, 18, 7, 'Too heavy for my taste but tasty.'),
(4, 19, 9, 'Fresh and delicious seafood!'),
(4, 20, 8, 'Great flavors, portion was small.'),
(4, 21, 10, 'One of the best seafood dishes ever.'),
(5, 22, 10, 'Crisp greens and excellent feta.'),
(5, 23, 9, 'Fresh and tasty, perfect salad.'),
(6, 24, 9, 'Rich chocolate flavor, perfect texture.'),
(6, 25, 10, 'Best mousse I’ve had, light and airy.'),
(7, 26, 9, 'Tiramisu was creamy and not too sweet.'),
(7, 27, 8, 'Good but could use more coffee flavor.'),
(8, 28, 10, 'Salmon was grilled to perfection!'),
(8, 29, 9, 'Fresh vegetables complemented it well.'),
(9, 30, 10, 'Tender beef and rich sauce, amazing.'),
(9, 31, 9, 'Perfectly cooked steak, excellent.'),
(10, 32, 8, 'Vegetables were fresh, risotto nice.'),
(10, 33, 7, 'Needed a bit more seasoning.'),
(11, 34, 9, 'Simple and delicious salad.'),
(11, 35, 8, 'Good balance of flavors.'),
(12, 36, 9, 'Tuna was fresh and tasty.'),
(12, 37, 8, 'Good dish, slightly too salty.'),
(13, 38, 9, 'Smooth panna cotta, great texture.'),
(13, 39, 10, 'Absolutely loved it, must try!'),
(14, 40, 9, 'Nice selection of cheeses, fresh.'),
(15, 11, 8, 'Classic pizza, simple and good.'),
(15, 12, 9, 'Loved the thin crust and flavor.'),
(16, 13, 9, 'Fresh veggies and great pasta.'),
(16, 14, 8, 'Light and tasty, loved it.'),
(17, 15, 10, 'Lasagna was hearty and rich.'),
(17, 16, 9, 'Perfect layers and taste.'),
(18, 17, 9, 'Fresh and tasty bruschetta.'),
(18, 18, 8, 'Good snack with nice flavors.'),
(19, 19, 9, 'Gnocchi were soft and flavorful.'),
(19, 20, 8, 'Pesto sauce was spot on.'),
(20, 21, 9, 'Tiramisu was delightful.'),
(20, 22, 8, 'Would like a bit stronger coffee taste.'),
(21, 23, 10, 'Affogato was heavenly, loved it.'),
(21, 24, 9, 'Perfect espresso and ice cream combo.'),
(22, 25, 10, 'Outstanding quality of fish roe.'),
(22, 26, 9, 'Fresh and delicious treat.'),
(23, 27, 9, 'Tender beef, hearty and rich.'),
(23, 28, 8, 'Good stew, very comforting.'),
(24, 29, 8, 'Simple but very tasty vegetables.'),
(24, 30, 9, 'Grilled to perfection.'),
(25, 31, 8, 'Herring was fresh and tasty.'),
(25, 32, 7, 'Good, but could be better.'),
(26, 33, 9, 'Rhubarb pie was sweet and tangy.'),
(26, 34, 10, 'Amazing dessert, loved it.'),
(27, 35, 9, 'Rich soup, perfect for seafood lovers.'),
(27, 36, 8, 'Good flavors, a bit heavy.'),
(28, 37, 9, 'Chocolate cake was moist and rich.'),
(28, 38, 8, 'Good but a bit sweet for me.'),
(29, 39, 10, 'Refreshing salad, great feta.'),
(29, 40, 9, 'Loved the freshness of ingredients.'),
(30, 11, 9, 'Tasty shrimp, nice kick of spice.'),
(30, 12, 8, 'Fresh toppings made it awesome.'),
(31, 13, 9, 'Loved the pesto flavor!'),
(31, 14, 8, 'Good but needed more sauce.'),
(32, 15, 8, 'Creamy and full of flavor.'),
(32, 16, 7, 'Soup was good, slightly salty.'),
(33, 17, 9, 'Molten center was amazing!'),
(33, 18, 10, 'Best chocolate fondant I have had.'),
(34, 19, 8, 'Nice carrot cake, very moist.'),
(34, 20, 9, 'Loved the cream cheese topping.'),
(35, 21, 9, 'Fresh fruits, nice presentation.'),
(35, 22, 8, 'Good selection, nicely done.'),
(36, 23, 9, 'Spicy and crispy wings!'),
(36, 24, 8, 'Good, but very spicy.'),
(37, 25, 9, 'Tender ribs, flavorful sauce.'),
(37, 26, 8, 'Well cooked, slightly fatty.'),
(38, 27, 8, 'Fresh wrap, loved it.'),
(38, 28, 7, 'Good, but could use more sauce.'),
(39, 29, 9, 'Loaded nachos, great flavor.'),
(39, 30, 8, 'Cheese melted perfectly.'),
(40, 31, 8, 'Tasty veggie burger.'),
(40, 32, 9, 'Great plant-based option.'),
(41, 33, 9, 'Cheesecake was smooth and rich.'),
(41, 34, 10, 'Best berry sauce ever.'),
(42, 35, 9, 'Thick milkshake, loved it.'),
(42, 36, 8, 'Good flavor options.'),
(43, 37, 9, 'Fish was crispy, loved it.'),
(43, 38, 8, 'Mushy peas were nice addition.'),
(44, 39, 10, 'Pie was hearty and flavorful.'),
(44, 40, 9, 'Perfect comfort food.'),
(45, 11, 9, 'Cheese and pickles were great.'),
(45, 12, 8, 'Classic lunch, done well.'),
(46, 13, 9, 'Sausages and mash were perfect.'),
(46, 14, 8, 'Good, but mash could be creamier.'),
(47, 15, 9, 'Rich and hearty pie.'),
(47, 16, 8, 'Good, a little heavy though.'),
(48, 17, 10, 'Sticky pudding was divine!'),
(48, 18, 9, 'Rich toffee flavor, amazing.'),
(49, 19, 8, 'Crispy pork scratchings, very tasty.'),
(49, 20, 7, 'Good snack with apple sauce.'),
(50, 21, 9, 'Fresh tartare, nice seasoning.');
(51, 22, 9, 'Delicious beef tartare, fresh and flavorful.'),
(51, 23, 8, 'Loved the texture, seasoning was spot on.'),
(52, 24, 9, 'Perfectly cooked pike perch, very tasty.'),
(52, 25, 8, 'Fish was tender and fresh.'),
(53, 26, 9, 'Rich mushroom flavor, loved the risotto.'),
(53, 27, 8, 'Creamy and satisfying dish.'),
(54, 28, 10, 'Lamb chops were juicy and cooked perfectly.'),
(54, 29, 9, 'Fantastic flavor, tender meat.'),
(55, 30, 8, 'Surprisingly tasty cauliflower steak.'),
(55, 31, 9, 'Delicious vegetarian option, full of flavor.'),
(56, 32, 9, 'Bright lemon flavor, perfect tart.'),
(56, 33, 8, 'Refreshing and not too sweet.'),
(57, 34, 9, 'Great cheese selection, loved it.'),
(57, 35, 8, 'Tasty but a bit pricey.'),
(58, 36, 10, 'Smoked salmon was fresh and delicious!'),
(58, 37, 9, 'Loved the cream cheese combo.'),
(59, 38, 10, 'Duck breast was juicy with amazing sauce.'),
(59, 39, 9, 'Perfectly cooked, rich flavors.'),
(60, 40, 9, 'Fresh and colorful vegan bowl.'),
(60, 11, 8, 'Healthy and delicious meal.'),
(61, 12, 10, 'Outstanding Beef Wellington, very rich!'),
(61, 13, 9, 'Perfectly cooked and full of flavor.'),
(62, 14, 9, 'Refreshing raspberry sorbet, loved it.'),
(62, 15, 8, 'Great light dessert after a heavy meal.'),
(63, 16, 9, 'Warm and comforting apple crumble.'),
(63, 17, 10, 'Best dessert I had here!'),
(64, 18, 8, 'Fresh pasta with nice vegetables.'),
(64, 19, 9, 'Simple and very flavorful.'),
(65, 20, 9, 'Fun pizza, kebab was well seasoned.'),
(65, 21, 8, 'Good mix of flavors, nice crust.'),
(66, 22, 9, 'Falafel wrap was fresh and delicious.'),
(66, 23, 8, 'Good but needed more sauce.'),
(67, 24, 9, 'Hearty doner plate, very satisfying.'),
(67, 25, 8, 'Tasty but a little oily.'),
(68, 26, 9, 'Fresh vegetarian pizza, well made.'),
(68, 27, 8, 'Toppings were great, crust was thin and crispy.'),
(69, 28, 9, 'Sweet baklava, perfect dessert size.'),
(69, 29, 8, 'Rich and flaky, really good.'),
(70, 30, 9, 'Refreshing mango lassi, nice and thick.'),
(70, 31, 8, 'Could be a little sweeter, but good.');